Repository gaji-market/gaji-market, pull requests merged in 2022-10, with the labels that each got.

#1 feat: add appbar
  front/src/App.js
  front/src/layouts/AppBar.jsx
Labels: feat

#15 feat: 공통 Card 컴포넌트
  front/src/components/.gitkeep
  front/src/components/Card.jsx
Labels: feat

#14 test: add example of redux slice
  front/src/layouts/AppBar.jsx
  front/src/pages/SliceTest.jsx
  front/src/pages/index.js
  front/src/routes/index.jsx
  front/src/store/store.js
  front/src/store/tempSlice.js
Labels: test

#23 리액트 아이콘 적용
  front/src/components/Card.jsx
  front/src/pages/Home.jsx
Labels: refactor

#26 버튼, 상태 뱃지 컴포넌트 및 테스트
  front/src/components/common/Button.jsx
  front/src/components/common/Card.jsx
  front/src/components/common/StateBadge.jsx
  front/src/components/common/commonColor.js
  front/src/pages/Home.jsx
Labels: feat, test
