Repository gaji-market/gaji-market, pull requests merged in 2023-01, with the labels that each got.

#47 11 add socket lib chatroom page - style 적용 전
  front/.env
  front/.gitignore
  front/package-lock.json
  front/package.json
  front/src/components/common/commonColor.js
  front/src/pages/Chat.jsx
  front/src/pages/index.js
  front/src/routes/index.jsx
  front/src/services/chatApi.js
  front/src/store/store.js
Labels: feat

#110 상품 카테고리 분류 구현, 상세보기 페이지 캐러셀 추가
  front/src/components/common/Button.jsx
  front/src/components/common/Card.jsx
  front/src/layouts/AppBar.jsx
  front/src/pages/Editor.jsx
  front/src/pages/ProductDetailView.jsx
  front/src/pages/ProductView.jsx
  front/src/services/productApi.js
  front/src/styles/editor.scss
  front/src/utils/.gitkeep
  front/src/utils/deduplicationState.js
Labels: feat

#93 Session slice
  front/.env
  front/package-lock.json
  front/package.json
  front/src/components/common/Modal.jsx
  front/src/layouts/AppBar.jsx
  front/src/pages/Login.jsx
  front/src/pages/MyPage.jsx
  front/src/pages/ProductView.jsx
  front/src/pages/SignUp.jsx
  front/src/routes/index.jsx
  front/src/store/sessionSlice.js
  front/src/store/store.js
  front/src/utils/crypto.js
Labels: feat

#125 112 search
  front/.gitignore
  front/src/components/common/ToggleSwitch.jsx
  front/src/layouts/AppBar.jsx
  front/src/pages/Home.jsx
  front/src/pages/SearchPage.jsx
  front/src/pages/index.js
  front/src/routes/index.jsx
  front/src/services/productApi.js
Labels: feat

#130 129 fixed appbar
  front/src/layouts/AppBar.jsx
  front/src/routes/index.jsx
Labels: refactor

#128 126 sidebar with category
  front/src/layouts/SideBar.jsx
  front/src/services/productApi.js
Labels: feat

#132 ProductView 코드 리팩토링, 좋아요/신고하기 기능 추가
  front/src/components/common/Card.jsx
  front/src/constants/productView.js
  front/src/pages/Chat.jsx
  front/src/pages/Editor.jsx
  front/src/pages/ProductDetailView.jsx
  front/src/pages/ProductView.jsx
  front/src/services/productApi.js
Labels: bug, refactor, feat

#140 Editor 페이지 1차 리팩토링 진행, 살래요 이미지 없이 등록, 수정하기 폼 데이터 바인딩
  front/src/assets/no_image.png
  front/src/components/Editor/SelectBox.jsx
  front/src/components/common/Card.jsx
  front/src/components/common/Checkbox.jsx
  front/src/components/common/Hashtag.jsx
  front/src/components/common/Slider.jsx
  front/src/constants/editor.js
  front/src/constants/hashtag.js
  front/src/pages/Editor.jsx
  front/src/pages/ProductDetailView.jsx
  front/src/routes/index.jsx
  front/src/services/productApi.js
  front/src/styles/editor.scss
  front/src/utils/isAllMoreThen.js
  front/src/utils/isIncludes.js
  front/src/utils/removeTargetImage.js
  front/src/utils/splitClassNameSpacing.js
Labels: refactor, feat

#136 로딩창 화면 완성
  front/src/components/common/Loading.jsx
  front/src/components/common/MyPageCard.jsx
  front/src/components/common/Toast.jsx
  front/src/pages/Login.jsx
  front/src/pages/MyEditPage.jsx
  front/src/pages/MyPage.jsx
  front/src/services/signUpApi.js
Labels: feat

#148 삭제 버그 수정, 이미지 fetch 할 때 에러 발생 시 error처리
  front/src/components/common/Slider.jsx
  front/src/pages/Editor.jsx
Labels: bug

#154 UI/UX 디자인 통일 작업 및 자잘한 코드 수정
  front/public/index.html
  front/src/assets/bg_bottom.png
  front/src/assets/bg_pattern.png
  front/src/assets/man.png
  front/src/assets/woman.png
  front/src/components/Mypage/MyPageCard.jsx
  front/src/components/common/DecoFooter.jsx
  front/src/components/common/Footer.jsx
  front/src/components/common/InputTitle.jsx
  front/src/components/common/Modal.jsx
  front/src/components/common/StarRate.jsx
  front/src/components/common/Toast.jsx
  front/src/layouts/AppBar.jsx
  front/src/layouts/Layout.jsx
  front/src/layouts/Layout_WithoutAppBar.jsx
  front/src/pages/Editor.jsx
  front/src/pages/Login.jsx
  front/src/pages/MyEditPage.jsx
  front/src/pages/MyPage.jsx
  front/src/pages/MyPageDetail.jsx
  front/src/pages/ProductDetailView.jsx
  front/src/pages/SignUp.jsx
  front/src/routes/index.jsx
  front/src/styles/editor.scss
Labels: refactor
